#!/usr/bin/env node
/**
 * Production web static build for Vercel (Phase 7).
 * Copies the existing SPA (index.html + assets) — no UI redesign.
 * Injects public GHOST_API_BASE_URL only.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'dist', 'web');

function copyFile(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else copyFile(from, to);
  }
}

function assertNoServerSecrets(text, label) {
  const forbidden = [
    /DATABASE_URL\s*=\s*postgresql:\/\/[^:]+:[^@\s]+@/i,
    /ACCESS_TOKEN_SECRET\s*=\s*(?!replace-with)[A-Za-z0-9+/=_-]{32,}/,
    /REFRESH_TOKEN_SECRET\s*=\s*(?!replace-with)[A-Za-z0-9+/=_-]{32,}/,
    /BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY/
  ];
  for (const pattern of forbidden) {
    if (pattern.test(text)) {
      throw new Error(`Refusing to ship server secret pattern in ${label}`);
    }
  }
}

// 1) Rebuild auth bundle from src/
const bundle = spawnSync('npm', ['run', 'auth:bundle'], {
  cwd: root,
  stdio: 'inherit',
  shell: process.platform === 'win32'
});
if (bundle.status !== 0) {
  process.exit(bundle.status || 1);
}

// 2) Clean output
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

// 3) Copy SPA assets
copyFile(path.join(root, 'index.html'), path.join(outDir, 'index.html'));
copyDir(path.join(root, 'assets'), path.join(outDir, 'assets'));

// 4) Public API URL only (Vercel env: GHOST_API_BASE_URL)
const apiBase =
  (process.env.GHOST_API_BASE_URL || process.env.API_PUBLIC_URL || '').trim().replace(/\/+$/, '') ||
  'http://127.0.0.1:3000';

if (/^\s*$/.test(apiBase)) {
  throw new Error('GHOST_API_BASE_URL must be a non-empty public API origin');
}

let parsed;
try {
  parsed = new URL(apiBase);
} catch {
  throw new Error(`Invalid GHOST_API_BASE_URL: ${apiBase}`);
}

const isLoopback =
  parsed.hostname === 'localhost' || parsed.hostname === '127.0.0.1' || parsed.hostname === '::1';
if (process.env.VERCEL === '1' || process.env.GHOST_WEB_PRODUCTION === '1') {
  if (parsed.protocol !== 'https:' && !isLoopback) {
    throw new Error('Production web builds require HTTPS GHOST_API_BASE_URL (or loopback for local verify)');
  }
}

const configJs = `/**
 * Generated by scripts/build-web.mjs — public client config only.
 * Do not add DATABASE_URL or token secrets here.
 */
window.GHOST_API_BASE_URL = ${JSON.stringify(apiBase)};
`;
fs.writeFileSync(path.join(outDir, 'assets', 'config.js'), configJs, 'utf8');

// 5) Lightweight CSP meta for hosted web (Electron still applies CSP in main)
const connectSrc = ["'self'", apiBase];
if (isLoopback) {
  connectSrc.push('http://127.0.0.1:3000', 'http://localhost:3000');
}
const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: https:",
  `connect-src ${connectSrc.join(' ')}`,
  "object-src 'none'",
  "base-uri 'self'",
  "frame-ancestors 'none'"
].join('; ');

const htmlPath = path.join(outDir, 'index.html');
let html = fs.readFileSync(htmlPath, 'utf8');
if (!/<meta\s+http-equiv=["']Content-Security-Policy["']/i.test(html)) {
  html = html.replace(
    /<head([^>]*)>/i,
    `<head$1>\n<meta http-equiv="Content-Security-Policy" content="${csp.replace(/"/g, '&quot;')}">`
  );
  fs.writeFileSync(htmlPath, html, 'utf8');
}

// 6) Bundle secret scan on output
for (const rel of ['assets/auth.bundle.js', 'assets/config.js', 'index.html']) {
  const full = path.join(outDir, rel);
  assertNoServerSecrets(fs.readFileSync(full, 'utf8'), rel);
  const text = fs.readFileSync(full, 'utf8');
  if (
    /@supabase\/supabase-js|lkbdybejiiijocnhwmvm\.supabase\.co/i.test(text) ||
    text.includes('sb_' + 'publishable_')
  ) {
    throw new Error(`Supabase runtime residue found in ${rel}`);
  }
}

process.stdout.write(`Web build ready: ${outDir}\n`);
process.stdout.write(`GHOST_API_BASE_URL=${apiBase}\n`);
